kind: pipeline
type: kubernetes
name: feature

steps:
  - name: retrieve cache
    image: ghcr.io/teamyapp/drone-cache:0.1.9
    volumes:
      - name: go-mod-cache
        path: /go/pkg/mod
      - name: cache
        path: /var/lib/cache
    settings:
      mode: retrieve
      version_file_path: go.sum
      cacheable_absolute_paths:
        - /go/pkg/mod
      storage_type: volume
      volume_cache_root_dir: /var/lib/cache
  - name: run unit tests
    image: golang:1.20
    volumes:
      - name: go-mod-cache
        path: /go/pkg/mod
    commands:
      - go test ./...
  - name: persist cache
    image: ghcr.io/teamyapp/drone-cache:0.1.9
    volumes:
      - name: go-mod-cache
        path: /go/pkg/mod
      - name: cache
        path: /var/lib/cache
    settings:
      mode: persist
      version_file_path: go.sum
      cacheable_absolute_paths:
        - /go/pkg/mod
      storage_type: volume
      volume_cache_root_dir: /var/lib/cache
volumes:
  - name: go-mod-cache
    temp: { }
  - name: cache
    host:
      path: /var/lib/cache
trigger:
  branch:
    - master
    - main
  event:
    - pull_request
