kind: pipeline
type: kubernetes
name: feature

steps:
  - name: restore cache
    image: ghcr.io/teamyapp/drone-cache
    volumes:
      - name: cache
        path: /go/pkg/mod
    settings:
      debug: true
      s3_endpoint: https://sfo3.digitaloceanspaces.com
      s3_access_key_id:
        from_secret: SPACE_ACCESS_KEY
      s3_secret:
        from_secret: SPACE_SECRET
      s3_bucket: teamyapp
      remote_root_dir: cache/go
      build: true
      cacheable_absolute_paths:
        - /go/pkg/mod
  - name: run unit tests
    image: golang:1.18
    volumes:
      - name: cache
        path: /go/pkg/mod
    commands:
      - go test ./...
  - name: refresh cache
    image: ghcr.io/teamyapp/drone-cache
    volumes:
      - name: cache
        path: /go/pkg/mod
    settings:
      debug: true
      s3_endpoint: https://sfo3.digitaloceanspaces.com
      s3_access_key_id:
        from_secret: SPACE_ACCESS_KEY
      s3_secret:
        from_secret: SPACE_SECRET
      s3_bucket: teamyapp
      remote_root_dir: cache/go
      refresh: true
      cacheable_absolute_paths:
        - /go/pkg/mod
volumes:
  - name: cache
    temp: {}
trigger:
  branch:
    - master
    - main
  event:
    - pull_request
